/* soapBasicHttpBinding_USCOREIServiceObject.h
   Generated by gSOAP 2.8.9 from test.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapBasicHttpBinding_USCOREIServiceObject_H
#define soapBasicHttpBinding_USCOREIServiceObject_H
#include "soapH.h"

/******************************************************************************\
 *                                                                            *
 * Service Object                                                             *
 *                                                                            *
\******************************************************************************/

class BasicHttpBinding_USCOREIServiceService : public soap
{    public:
	BasicHttpBinding_USCOREIServiceService()
	{ static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://tempuri.org/Imports", NULL, NULL},
	{"ns2", "http://schemas.microsoft.com/2003/10/Serialization/Arrays", NULL, NULL},
	{"tempuri", "http://tempuri.org/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};

	this->namespaces = namespaces; };
	virtual ~BasicHttpBinding_USCOREIServiceService() { };
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog) { return soap_bind(this, host, port, backlog); };
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept() { return soap_accept(this); };
#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
	/// Then accept SSL handshake, when SSL is used
	virtual	int ssl_accept() { return soap_ssl_accept(this); };
#endif
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve() { return soap_serve(this); };
};

/******************************************************************************\
 *                                                                            *
 * Service Operations (you should define these globally)                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Getstring(struct soap*, _tempuri__Getstring *tempuri__Getstring, _tempuri__GetstringResponse *tempuri__GetstringResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__ExecuteNonQuery(struct soap*, _tempuri__ExecuteNonQuery *tempuri__ExecuteNonQuery, _tempuri__ExecuteNonQueryResponse *tempuri__ExecuteNonQueryResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__ExecuteScalar_USCOREBool(struct soap*, _tempuri__ExecuteScalar_USCOREBool *tempuri__ExecuteScalar_USCOREBool, _tempuri__ExecuteScalar_USCOREBoolResponse *tempuri__ExecuteScalar_USCOREBoolResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__ExecuteScalar_USCOREString(struct soap*, _tempuri__ExecuteScalar_USCOREString *tempuri__ExecuteScalar_USCOREString, _tempuri__ExecuteScalar_USCOREStringResponse *tempuri__ExecuteScalar_USCOREStringResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__ExecuteScalar_USCOREObject(struct soap*, _tempuri__ExecuteScalar_USCOREObject *tempuri__ExecuteScalar_USCOREObject, _tempuri__ExecuteScalar_USCOREObjectResponse *tempuri__ExecuteScalar_USCOREObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__DataAdapter(struct soap*, _tempuri__DataAdapter *tempuri__DataAdapter, _tempuri__DataAdapterResponse *tempuri__DataAdapterResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__ExecuteSqlTransaction_USCOREBool(struct soap*, _tempuri__ExecuteSqlTransaction_USCOREBool *tempuri__ExecuteSqlTransaction_USCOREBool, _tempuri__ExecuteSqlTransaction_USCOREBoolResponse *tempuri__ExecuteSqlTransaction_USCOREBoolResponse);

#endif
