/* soapBasicHttpBinding_USCOREIServiceProxy.h
   Generated by gSOAP 2.8.9 from test.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapBasicHttpBinding_USCOREIServiceProxy_H
#define soapBasicHttpBinding_USCOREIServiceProxy_H
#include "soapH.h"
class BasicHttpBinding_USCOREIService
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'BasicHttpBinding_USCOREIService' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	BasicHttpBinding_USCOREIService()
    { soap = soap_new(); endpoint = "http://198.168.0.253:7788/LT_WCF"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://tempuri.org/Imports", NULL, NULL},
	{"ns2", "http://schemas.microsoft.com/2003/10/Serialization/Arrays", NULL, NULL},
	{"tempuri", "http://tempuri.org/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~BasicHttpBinding_USCOREIService() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'Getstring' of service 'BasicHttpBinding_USCOREIService' and return error code (or SOAP_OK)
	virtual int __tempuri__Getstring(_tempuri__Getstring *tempuri__Getstring, _tempuri__GetstringResponse *tempuri__GetstringResponse) { return soap ? soap_call___tempuri__Getstring(soap, endpoint, NULL, tempuri__Getstring, tempuri__GetstringResponse) : SOAP_EOM; };
	/// Invoke 'ExecuteNonQuery' of service 'BasicHttpBinding_USCOREIService' and return error code (or SOAP_OK)
	virtual int __tempuri__ExecuteNonQuery(_tempuri__ExecuteNonQuery *tempuri__ExecuteNonQuery, _tempuri__ExecuteNonQueryResponse *tempuri__ExecuteNonQueryResponse) { return soap ? soap_call___tempuri__ExecuteNonQuery(soap, endpoint, NULL, tempuri__ExecuteNonQuery, tempuri__ExecuteNonQueryResponse) : SOAP_EOM; };
	/// Invoke 'ExecuteScalar_Bool' of service 'BasicHttpBinding_USCOREIService' and return error code (or SOAP_OK)
	virtual int __tempuri__ExecuteScalar_USCOREBool(_tempuri__ExecuteScalar_USCOREBool *tempuri__ExecuteScalar_USCOREBool, _tempuri__ExecuteScalar_USCOREBoolResponse *tempuri__ExecuteScalar_USCOREBoolResponse) { return soap ? soap_call___tempuri__ExecuteScalar_USCOREBool(soap, endpoint, NULL, tempuri__ExecuteScalar_USCOREBool, tempuri__ExecuteScalar_USCOREBoolResponse) : SOAP_EOM; };
	/// Invoke 'ExecuteScalar_String' of service 'BasicHttpBinding_USCOREIService' and return error code (or SOAP_OK)
	virtual int __tempuri__ExecuteScalar_USCOREString(_tempuri__ExecuteScalar_USCOREString *tempuri__ExecuteScalar_USCOREString, _tempuri__ExecuteScalar_USCOREStringResponse *tempuri__ExecuteScalar_USCOREStringResponse) { return soap ? soap_call___tempuri__ExecuteScalar_USCOREString(soap, endpoint, NULL, tempuri__ExecuteScalar_USCOREString, tempuri__ExecuteScalar_USCOREStringResponse) : SOAP_EOM; };
	/// Invoke 'ExecuteScalar_Object' of service 'BasicHttpBinding_USCOREIService' and return error code (or SOAP_OK)
	virtual int __tempuri__ExecuteScalar_USCOREObject(_tempuri__ExecuteScalar_USCOREObject *tempuri__ExecuteScalar_USCOREObject, _tempuri__ExecuteScalar_USCOREObjectResponse *tempuri__ExecuteScalar_USCOREObjectResponse) { return soap ? soap_call___tempuri__ExecuteScalar_USCOREObject(soap, endpoint, NULL, tempuri__ExecuteScalar_USCOREObject, tempuri__ExecuteScalar_USCOREObjectResponse) : SOAP_EOM; };
	/// Invoke 'DataAdapter' of service 'BasicHttpBinding_USCOREIService' and return error code (or SOAP_OK)
	virtual int __tempuri__DataAdapter(_tempuri__DataAdapter *tempuri__DataAdapter, _tempuri__DataAdapterResponse *tempuri__DataAdapterResponse) { return soap ? soap_call___tempuri__DataAdapter(soap, endpoint, NULL, tempuri__DataAdapter, tempuri__DataAdapterResponse) : SOAP_EOM; };
	/// Invoke 'ExecuteSqlTransaction_Bool' of service 'BasicHttpBinding_USCOREIService' and return error code (or SOAP_OK)
	virtual int __tempuri__ExecuteSqlTransaction_USCOREBool(_tempuri__ExecuteSqlTransaction_USCOREBool *tempuri__ExecuteSqlTransaction_USCOREBool, _tempuri__ExecuteSqlTransaction_USCOREBoolResponse *tempuri__ExecuteSqlTransaction_USCOREBoolResponse) { return soap ? soap_call___tempuri__ExecuteSqlTransaction_USCOREBool(soap, endpoint, NULL, tempuri__ExecuteSqlTransaction_USCOREBool, tempuri__ExecuteSqlTransaction_USCOREBoolResponse) : SOAP_EOM; };
};
#endif
