/* soapServer.cpp
   Generated by gSOAP 2.8.9 from test.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.9 2012-08-24 02:27:07 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:Getstring"))
		return soap_serve___tempuri__Getstring(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:ExecuteNonQuery"))
		return soap_serve___tempuri__ExecuteNonQuery(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:ExecuteScalar_Bool"))
		return soap_serve___tempuri__ExecuteScalar_USCOREBool(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:ExecuteScalar_String"))
		return soap_serve___tempuri__ExecuteScalar_USCOREString(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:ExecuteScalar_Object"))
		return soap_serve___tempuri__ExecuteScalar_USCOREObject(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:DataAdapter"))
		return soap_serve___tempuri__DataAdapter(soap);
	if (!soap_match_tag(soap, soap->tag, "tempuri:ExecuteSqlTransaction_Bool"))
		return soap_serve___tempuri__ExecuteSqlTransaction_USCOREBool(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Getstring(struct soap *soap)
{	struct __tempuri__Getstring soap_tmp___tempuri__Getstring;
	_tempuri__GetstringResponse tempuri__GetstringResponse;
	tempuri__GetstringResponse.soap_default(soap);
	soap_default___tempuri__Getstring(soap, &soap_tmp___tempuri__Getstring);
	soap->encodingStyle = NULL;
	if (!soap_get___tempuri__Getstring(soap, &soap_tmp___tempuri__Getstring, "-tempuri:Getstring", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__Getstring(soap, soap_tmp___tempuri__Getstring.tempuri__Getstring, &tempuri__GetstringResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	tempuri__GetstringResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tempuri__GetstringResponse.soap_put(soap, "tempuri:GetstringResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tempuri__GetstringResponse.soap_put(soap, "tempuri:GetstringResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__ExecuteNonQuery(struct soap *soap)
{	struct __tempuri__ExecuteNonQuery soap_tmp___tempuri__ExecuteNonQuery;
	_tempuri__ExecuteNonQueryResponse tempuri__ExecuteNonQueryResponse;
	tempuri__ExecuteNonQueryResponse.soap_default(soap);
	soap_default___tempuri__ExecuteNonQuery(soap, &soap_tmp___tempuri__ExecuteNonQuery);
	soap->encodingStyle = NULL;
	if (!soap_get___tempuri__ExecuteNonQuery(soap, &soap_tmp___tempuri__ExecuteNonQuery, "-tempuri:ExecuteNonQuery", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__ExecuteNonQuery(soap, soap_tmp___tempuri__ExecuteNonQuery.tempuri__ExecuteNonQuery, &tempuri__ExecuteNonQueryResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	tempuri__ExecuteNonQueryResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tempuri__ExecuteNonQueryResponse.soap_put(soap, "tempuri:ExecuteNonQueryResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tempuri__ExecuteNonQueryResponse.soap_put(soap, "tempuri:ExecuteNonQueryResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__ExecuteScalar_USCOREBool(struct soap *soap)
{	struct __tempuri__ExecuteScalar_USCOREBool soap_tmp___tempuri__ExecuteScalar_USCOREBool;
	_tempuri__ExecuteScalar_USCOREBoolResponse tempuri__ExecuteScalar_USCOREBoolResponse;
	tempuri__ExecuteScalar_USCOREBoolResponse.soap_default(soap);
	soap_default___tempuri__ExecuteScalar_USCOREBool(soap, &soap_tmp___tempuri__ExecuteScalar_USCOREBool);
	soap->encodingStyle = NULL;
	if (!soap_get___tempuri__ExecuteScalar_USCOREBool(soap, &soap_tmp___tempuri__ExecuteScalar_USCOREBool, "-tempuri:ExecuteScalar_Bool", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__ExecuteScalar_USCOREBool(soap, soap_tmp___tempuri__ExecuteScalar_USCOREBool.tempuri__ExecuteScalar_USCOREBool, &tempuri__ExecuteScalar_USCOREBoolResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	tempuri__ExecuteScalar_USCOREBoolResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tempuri__ExecuteScalar_USCOREBoolResponse.soap_put(soap, "tempuri:ExecuteScalar_BoolResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tempuri__ExecuteScalar_USCOREBoolResponse.soap_put(soap, "tempuri:ExecuteScalar_BoolResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__ExecuteScalar_USCOREString(struct soap *soap)
{	struct __tempuri__ExecuteScalar_USCOREString soap_tmp___tempuri__ExecuteScalar_USCOREString;
	_tempuri__ExecuteScalar_USCOREStringResponse tempuri__ExecuteScalar_USCOREStringResponse;
	tempuri__ExecuteScalar_USCOREStringResponse.soap_default(soap);
	soap_default___tempuri__ExecuteScalar_USCOREString(soap, &soap_tmp___tempuri__ExecuteScalar_USCOREString);
	soap->encodingStyle = NULL;
	if (!soap_get___tempuri__ExecuteScalar_USCOREString(soap, &soap_tmp___tempuri__ExecuteScalar_USCOREString, "-tempuri:ExecuteScalar_String", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__ExecuteScalar_USCOREString(soap, soap_tmp___tempuri__ExecuteScalar_USCOREString.tempuri__ExecuteScalar_USCOREString, &tempuri__ExecuteScalar_USCOREStringResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	tempuri__ExecuteScalar_USCOREStringResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tempuri__ExecuteScalar_USCOREStringResponse.soap_put(soap, "tempuri:ExecuteScalar_StringResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tempuri__ExecuteScalar_USCOREStringResponse.soap_put(soap, "tempuri:ExecuteScalar_StringResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__ExecuteScalar_USCOREObject(struct soap *soap)
{	struct __tempuri__ExecuteScalar_USCOREObject soap_tmp___tempuri__ExecuteScalar_USCOREObject;
	_tempuri__ExecuteScalar_USCOREObjectResponse tempuri__ExecuteScalar_USCOREObjectResponse;
	tempuri__ExecuteScalar_USCOREObjectResponse.soap_default(soap);
	soap_default___tempuri__ExecuteScalar_USCOREObject(soap, &soap_tmp___tempuri__ExecuteScalar_USCOREObject);
	soap->encodingStyle = NULL;
	if (!soap_get___tempuri__ExecuteScalar_USCOREObject(soap, &soap_tmp___tempuri__ExecuteScalar_USCOREObject, "-tempuri:ExecuteScalar_Object", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__ExecuteScalar_USCOREObject(soap, soap_tmp___tempuri__ExecuteScalar_USCOREObject.tempuri__ExecuteScalar_USCOREObject, &tempuri__ExecuteScalar_USCOREObjectResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	tempuri__ExecuteScalar_USCOREObjectResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tempuri__ExecuteScalar_USCOREObjectResponse.soap_put(soap, "tempuri:ExecuteScalar_ObjectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tempuri__ExecuteScalar_USCOREObjectResponse.soap_put(soap, "tempuri:ExecuteScalar_ObjectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__DataAdapter(struct soap *soap)
{	struct __tempuri__DataAdapter soap_tmp___tempuri__DataAdapter;
	_tempuri__DataAdapterResponse tempuri__DataAdapterResponse;
	tempuri__DataAdapterResponse.soap_default(soap);
	soap_default___tempuri__DataAdapter(soap, &soap_tmp___tempuri__DataAdapter);
	soap->encodingStyle = NULL;
	if (!soap_get___tempuri__DataAdapter(soap, &soap_tmp___tempuri__DataAdapter, "-tempuri:DataAdapter", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__DataAdapter(soap, soap_tmp___tempuri__DataAdapter.tempuri__DataAdapter, &tempuri__DataAdapterResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	tempuri__DataAdapterResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tempuri__DataAdapterResponse.soap_put(soap, "tempuri:DataAdapterResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tempuri__DataAdapterResponse.soap_put(soap, "tempuri:DataAdapterResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__ExecuteSqlTransaction_USCOREBool(struct soap *soap)
{	struct __tempuri__ExecuteSqlTransaction_USCOREBool soap_tmp___tempuri__ExecuteSqlTransaction_USCOREBool;
	_tempuri__ExecuteSqlTransaction_USCOREBoolResponse tempuri__ExecuteSqlTransaction_USCOREBoolResponse;
	tempuri__ExecuteSqlTransaction_USCOREBoolResponse.soap_default(soap);
	soap_default___tempuri__ExecuteSqlTransaction_USCOREBool(soap, &soap_tmp___tempuri__ExecuteSqlTransaction_USCOREBool);
	soap->encodingStyle = NULL;
	if (!soap_get___tempuri__ExecuteSqlTransaction_USCOREBool(soap, &soap_tmp___tempuri__ExecuteSqlTransaction_USCOREBool, "-tempuri:ExecuteSqlTransaction_Bool", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __tempuri__ExecuteSqlTransaction_USCOREBool(soap, soap_tmp___tempuri__ExecuteSqlTransaction_USCOREBool.tempuri__ExecuteSqlTransaction_USCOREBool, &tempuri__ExecuteSqlTransaction_USCOREBoolResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	tempuri__ExecuteSqlTransaction_USCOREBoolResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || tempuri__ExecuteSqlTransaction_USCOREBoolResponse.soap_put(soap, "tempuri:ExecuteSqlTransaction_BoolResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || tempuri__ExecuteSqlTransaction_USCOREBoolResponse.soap_put(soap, "tempuri:ExecuteSqlTransaction_BoolResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
